#!/bin/bash
# Generate STRUCTURE.md (folder tree) at the vault root.
VAULT="${1:-$PWD}"
OUT="$VAULT/STRUCTURE.md"

{
  echo "# Vault Structure"
  echo
  echo "_Auto-generated by scripts/tree_index.sh — do not edit by hand._"
  echo
  echo '```text'
  (cd "$VAULT" && find . -not -path './.git*' -not -path './.obsidian*' -not -path './graphify-out*' | sort | sed -e 's;[^/]*/;  ;g' -e 's;^  ;|-- ;')
  echo '```'
} > "$OUT"