#!/bin/bash
# Generate STRUCTURE.md (folder tree) at the vault root. Replaces the
# unmaintained "graphify" idea — Obsidian has a native graph view.
VAULT="${1:-$HOME/storage/shared/scepter}"
OUT="$VAULT/STRUCTURE.md"

{
  echo "# Vault Structure"
  echo
  echo "_Auto-generated by scripts/tree_index.sh — do not edit by hand._"
  echo
  echo '```text'
  (cd "$VAULT" && find . -not -path './.git*' -not -path './.obsidian*' | sort | sed -e 's;[^/]*/;  ;g' -e 's;^  ;|-- ;')
  echo '```'
} > "$OUT"
