#!/bin/bash
# tree_index.sh -- regenerate STRUCTURE.md from current vault layout
# Usage: tree_index.sh <vault_path>

VAULT="${1:-$HOME/scepter}"
OUT="$VAULT/STRUCTURE.md"

cd "$VAULT" || exit 1

{
    echo "# Vault Structure"
    echo ""
    echo "_Auto-generated by scripts/tree_index.sh -- do not edit by hand._"
    echo ""
    echo '```text'
    find . -type f \
        ! -path './.git/*' \
        ! -path './.obsidian/*' \
        ! -path './.hermes/*' \
        ! -name 'nohup.out' \
        | sed 's|^\./||' | sort | sed 's|[^/]*/|  |g; s|  |-- |'
    echo '```'
} > "$OUT"